name: Deploy package

on:
  release:
    types[published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy
      env:
        GITHUB_USERNAME: x-access-token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        mvn versions:set -DnewVersion={{ github.event.release.name }}
        mvn -s ./settings.xml deploy -U
